verus_git_url = "https://github.com/verus-lang/verus.git"
verus_refspec = "cvc5-compat"
verus_features = ["singular"]
verus_extra_args = ["-V", "cvc5"]

[[project]]
name = "verified-storage"
git_url = "https://github.com/microsoft/verified-storage.git"
refspec = "main"
crate_root = "storage_node/src/lib.rs"
extra_args = [
    "-L", "dependency=deps_hack/target/debug/deps",
    "--extern=deps_hack=deps_hack/target/debug/libdeps_hack.rlib",
]
prepare_script = """
DEBIAN_FRONTEND=noninteractive apt-get install -y libpmem1 libpmemlog1 libpmem-dev libpmemlog-dev llvm-dev clang libclang-dev # verified-storage

cd deps_hack
cargo clean
cargo +1.76.0 build
"""
