verus_git_url = "https://github.com/verus-lang/verus.git"
verus_refspec = "cvc5-compat"
verus_features = ["singular"]
verus_extra_args = ["-V", "cvc5"]
verus_verify_vstd = false

[[project]]
name = "node-replication"
git_url = "https://github.com/achreto/verified-node-replication.git"
refspec = "main"
crate_root = "verified-node-replication/src/lib.rs"
extra_args = ["--crate-type=dylib"]
